version: '3.8'

services:
  app:
    build: .
    container_name: bibliomane
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app  # Optional: Mounts the current directory for easier development
    restart: unless-stopped
