version: '3.8'

services:
  app:
    build: .
    container_name: bibliomane
    env_file: .env
#    ports:
#      - "3001:3001"
    volumes:
      - ${LIBRARY}:/app/hdd/books  # Optional: Mounts the current directory for easier development
    restart: unless-stopped

networks:
   nginx-proxy_default:
     external: true
