version: '3.8'

services:
  app:
    build: .
    container_name: bibliomane
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DOMAIN=${DOMAIN}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app  # Optional: Mounts the current directory for easier development
    restart: unless-stopped

    #healthcheck:
   #   test: ["CMD", "curl", "-f", "http://${Domain}/bibliomane"]
  #    interval: 1m
 #     timeout: 10s
#      retries: 3

#networks:
#  bibliomane_default:
#    external: true


