version: '3.8'

services:
  app:
    build: .
    container_name: bibliomane
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app  # Optional: Mounts the current directory for easier development
    restart: unless-stopped

    #healthcheck:
   #   test: ["CMD", "curl", "-f", "http://${Domain}/bibliomane"]
  #    interval: 1m
 #     timeout: 10s
#      retries: 3

networks:
  bibliomane_default:  # Reuse the shared network created by network_overview
    external: true


